### ISSUE TITLE
Error Parsing Pdf Turn file

### ISSUE THREAD

**Issue by HabaneroHolt** [JOverseer/joverseer#620]
Upgraded to 1.14 today
Build ID: 2015-11-26

On import of turn files, every pdf got this error:
Importing file 'E:\My Documents\Dad\MEPBM\FA146\T33\g146n18t033.pdf'.
org/txt2xml/config/ProcessorFactory
Error parsing Pdf Turn file.

**Comment by GnarlyDave** [comment]
Ah, it looks like a mistake in packaging up the update zip.

Version 1.14.0 puts *all* third party libraries into their own jar files, and it looks like a couple where missed from the update.zip file. The installer is fine. The two missing files are orderchecker.jar and txt2xml.jar

I'll release 1.14.1 shortly to fix it for the future.

The immediate fix is to run the installer downloaded from http://middleearthgames.com/down/joverseer-setup-1.14.0.exe. This will install to Program Files.

**Comment by GnarlyDave** [comment]
1.14.1 is now live and fixes the problem on two machines that I've tested.

**Comment by HabaneroHolt** [comment]
Thank you for the rapid fix. 


    On Monday, November 30, 2015 7:11 AM, Dave Spring <notifications@github.com> wrote:
 

 1.14.1 is now live and fixes the problem on two machines that I've tested.—
