### ISSUE TITLE
setup selected roads, vanishing

### ISSUE THREAD

**Issue by GnarlyDave** [JOverseer/joverseer#622]
reported by Jordi Chalmeta.
Kin strife, game 637..symptom is that roads of Arnor created by setup are not visible.
eg. hex 1307 should show a east-west road.
Debugging with a trap in MapPanel.java shows that there is more than one copy of the hex present.
One with the road present and another without...and the last one is rendered on top of the first.

In fact, the gm.getHexes() function is returning twice as a many hexes.
This suggests that the import function is messing up.

Note that Jordi is actually importing two nations (2 and 5).

**Comment by GnarlyDave** [comment]
# Workaround
1. put the turn files into separate directories, one per turn (put multiple nations for the same turn in the same directory.
2. import the game files in turn order, starting with turn0
3. save the .jov file.

**Comment by GnarlyDave** [comment]
A number of things seem to show this symptom.
1. not specifying new XML on the new game dialog..
2. Importing the turns in reverse order...although you get a dire, but vague warning.
3. Importing using the 'import game tree' option seems to import the files in the correct order but the display isn't correct.

**Comment by EdwardLaneUK** [comment]
workaround is not quite a fully functional solution - Dave is investigating
further

**Comment by GnarlyDave** [comment]
Jordi reports the workaround works for him :)
