### ISSUE TITLE
412 in 1.16.2 doesn't seem to be working.

### ISSUE THREAD

**Issue by randybias** [JOverseer/joverseer#649]
Maybe it's working, but it seems confused.  Basically when you pick "412" from the drop down, it adds a whole bunch of extra "parameters" as "-"s which at least seems to confuse the UI.

See attached screen grabs.

![412-order-problem](https://user-images.githubusercontent.com/25304/28991925-ae2c35e4-7944-11e7-852d-67416e2b6feb.jpeg)
![412-example](https://user-images.githubusercontent.com/25304/28991928-b141f692-7944-11e7-9064-e1126e89de29.jpeg)
![412-order-hover-over](https://user-images.githubusercontent.com/25304/28991929-b34a4de0-7944-11e7-8d0a-04d9addc6200.jpeg)

**Comment by EdwardLaneUK** [comment]
It is working - and spell 412 now allows up to 6 artifact parameters to be
passed, however the 'orderchecker' section of the code has not been told
that yet and so complains - param 11 to 15 are presumably the ones being
used by the new code expansion of the 412 spell.

**Comment by randybias** [comment]
I don't really understand the overall architecture of jOverseer yet, so I all I can do is observe without a lot of inferring.  What I can see is that orderchecker does not work as you pointed out.  It simply won't run.  Also, if you export orders the resulting "autoinput" file is broken.  And can't really be reimported.

Although if you "generate order report" the resulting text is correct and can be re-imported and then orderchecker even works with the resulting orders.  So, there is something about the way the UI is adding the extra parameters ("-"), storing that information, and then exporting it to a file and orderchecker.

So the cleanest workaround is you input everything into the GUI, ignore the errors, generate an order report.  Copy to a notepad.  Then delete your orders/turn, reimport the turn data (if you deleted the turn instead of the orders), then import orders from text.  That results in clean orders that can be run through orderchecker and it seems to work fine at that point unless you try and edit the orders again.

Strangely, some of my characters took the multiple RA orders without a problem through the UI.  The character that seems to have the problem is a "epic" character (3 commands).  It's also the first character I tried to edit the RA commands on.  Could just be a coincidence.

**Comment by GnarlyDave** [comment]
the 940 command is fine, if you don't change your mind about which spell you want..
I think it's trying to be clever when you change spells, and reuse the parameters that you just typed...but it all goes horribly wrong and keeps appending the parameters...clicking on the eraser fixes it.

**Comment by GnarlyDave** [comment]
closing.
