### ISSUE TITLE
Check Orders on Mac OS X is failing

### ISSUE THREAD

**Issue by ravenzachary** [JOverseer/joverseer#662]
When I attempt to run Check Orders after selecting my nation, I get this error every time:

Error!
The rules file (bin/metadata/orderchecker/ruleset.csv) could not be opened!

JOverseer Version 1.16.3
Build Id: 2018-4-13

macOS High Serra 10.13.4

Java 8 Update 171

Does anyone have a workaround for this? I am worried about submitting a turn with an error.

**Comment by GnarlyDave** [comment]
fixed by faf43d76599ef1eec03773ac9d30c7ff93a00203 . Expect in version 1.16.4 Real Soon Now .

**Comment by ravenzachary** [comment]
Thank you! You have just made my life easier and I appreciate it! : )
