### ISSUE TITLE
Game type selection does not match that found in the turn file on Mac

### ISSUE THREAD

**Issue by ravenzachary** [JOverseer/joverseer#669]
Check Orders now works on a Mac when running V1.16.4 (thank you!), but I get an error message when I first select Check Orders from the Game menu.

Error!

Game type selection does not match that found in the turn file.

Processing will continue...

**Comment by harry898bee** [comment]
Getting the same on PC, Win10

**Comment by GnarlyDave** [comment]
Note to me: check abbreviations and expansion for game type...Kin-Strife KIN vs KS.

**Comment by GnarlyDave** [comment]
I've finally tracked this down. It was just PBM games and it was benign. Fixed for 1.16.11
