### ISSUE TITLE
weird report on order checker

### ISSUE THREAD

**Issue by harbqll** [JOverseer/joverseer#686]
One of my mages is casting Greater Heal.

Order checker states "No rules exist for Greater Heal (6)."

Version:1.16.16
system properties
java.home:C:\Program Files (x86)\Java\jre1.8.0_211
java.vendor:Oracle Corporation
java.vendor.url:http://java.oracle.com/
java.version:1.8.0_211
os.arch:x86
os.name:Windows 10
os.version:10.0
C:\Users\harbq\AppData\Local\Temp\joverseer_8-18_1255329097655500833263202.log

**Comment by GnarlyDave** [comment]
the rule for GreaterHeal is missing from orderchecker's ruleset.csv
fixed in 1.16.18.
