### ISSUE TITLE
climate info not imported?

### ISSUE THREAD

**Issue by afeija** [JOverseer/joverseer#691]
would be nice to manually change it as well (in order to see outcome due to season changes)

**Comment by GnarlyDave** [comment]
Ah, this seems to have got lost now we don't parse the PDFs.
TurnNewXmlReader is failing to scan the parsed pop centres and apply the climate to the appropriate hex, like the PDF reader did.

**Comment by GnarlyDave** [comment]
fixed by 766f856e1f8106a6748010ed2510332c7e82a55a
so ready for 1.16.17
