### ISSUE TITLE
Nation Names

### ISSUE THREAD

**Issue by GnarlyDave** [JOverseer/joverseer#703]
I note that in JO, it calls nation 2 "The South >Kingdom" but nation 1 is just "North >Kingdom"Â just letting you know in case you >want to add this to your list of fixes. >
Jeremy

[from trello]
game type?

**Comment by EdwardLaneUK** [comment]
that's an inconsistancy from the FAS setup sheet - should be fixed in
future games without change to joverseer

Edward :)

**Comment by GnarlyDave** [comment]
it's a setup sheet issue, since that's where the nation names come from in Fourth Age games
