### ISSUE TITLE
Parsing order texts for naming character fails when no name is provided

### ISSUE THREAD

**Issue by thorsbro** [JOverseer/joverseer#747]
Name character commands can be issues without giving a name which will lead to a random name being given to the new character.

If such an order is imported into Joverseer it fails to recognize that no name is given and assign the gender letter "m/f" to the new name instead.

Potential fix, if there is no gender designation and the name is either "f" or "m" joverseer so interpret the name as the gender instead.

**Comment by GnarlyDave** [comment]
I've refactored the 'order text importing' code and added a number of tests to exercise it.
released in version 1.18.11
